// ============================================
// ECE HUB — COMPONENT DATA (Real Inventory)
// ============================================

const COMPONENTS = [

  // ─── DEVELOPMENT BOARDS ───────────────────

  {
    id: 1,
    name: "Arduino UNO",
    description: "The classic microcontroller board based on ATmega328P. Ideal for beginners and embedded projects. Features 14 digital I/O pins, 6 analog inputs, and USB connectivity.",
    category: "microcontroller",
    categoryLabel: "Development Board",
    icon: "🟦",
    image: "https://www.flyrobo.in/image/cache/wp/gj/arduino-uno-r3-smd-board-cable-for-arduino-uno-1/arduino-uno-r3-smd-board-cable-for-arduino-uno-14-550x550h.webp",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 149,
    project: "ECE Department Inventory",
    tech: ["ATmega328P", "Arduino IDE", "5V Logic"],
    features: ["14 digital I/O pins", "6 analog input pins", "16 MHz clock speed", "USB programming", "5V operating voltage"]
  },
  {
    id: 2,
    name: "ESP32 Development Board",
    description: "Powerful dual-core microcontroller with built-in Wi-Fi and Bluetooth. Perfect for IoT applications. Supports Arduino IDE and MicroPython.",
    category: "microcontroller",
    categoryLabel: "Development Board",
    icon: "🟩",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/20/ESP32_Espressif_ESP-WROOM-32_Dev_Board.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 199,
    project: "ECE Department Inventory",
    tech: ["Xtensa LX6", "Wi-Fi 802.11", "Bluetooth 4.2", "Arduino IDE"],
    features: ["Dual-core 240 MHz CPU", "Built-in Wi-Fi & Bluetooth", "34 GPIO pins", "4MB Flash memory", "Deep sleep support"]
  },
  {
    id: 3,
    name: "NodeMCU (ESP8266)",
    description: "Wi-Fi enabled microcontroller module based on ESP8266. Popular for IoT projects with built-in TCP/IP stack and easy Arduino IDE support.",
    category: "microcontroller",
    categoryLabel: "Development Board",
    icon: "🟧",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/7e/NodeMCU_DEVKIT_1.0.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 129,
    project: "ECE Department Inventory",
    tech: ["ESP8266", "Wi-Fi 802.11 b/g/n", "Lua / Arduino IDE"],
    features: ["Built-in Wi-Fi module", "11 digital I/O pins", "1 analog input pin", "USB-to-Serial (CH340)", "3.3V logic level"]
  },

  // ─── DISPLAY MODULES ──────────────────────

  {
    id: 4,
    name: "LCD Display (16x2 / 20x4)",
    description: "Character LCD display module. Available in 16x2 and 20x4 configurations. Connects via I2C backpack for minimal pin usage.",
    category: "display",
    categoryLabel: "Display",
    icon: "🖥️",
    image: "https://www.google.com/imgres?q=LCD%20Display%20(16x2%20%2F%2020x4)&imgurl=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F51swvRjWK0L.jpg&imgrefurl=https%3A%2F%2Fwww.amazon.in%2Fmodule-Display-4-Pin-Connection-Indicator%2Fdp%2FB0DVSPDFK3&docid=vHlUb6T47eOgDM&tbnid=LqMO4NtXOnDAZM&vet=12ahUKEwid9snPtfyUAxWP1TgGHa9vEKAQnPAOegQIGxAB..i&w=713&h=713&hcb=2&ved=2ahUKEwid9snPtfyUAxWP1TgGHa9vEKAQnPAOegQIGxAB",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 99,
    project: "ECE Department Inventory",
    tech: ["HD44780 Controller", "I2C Backpack", "Arduino Library"],
    features: ["16x2 or 20x4 character variants", "I2C interface (only 2 wires)", "Adjustable contrast", "Backlight control", "3.3V / 5V compatible"]
  },
  {
    id: 5,
    name: "OLED Display",
    description: "0.96-inch SSD1306 OLED display module with 128x64 pixel resolution. Ultra-low power, high contrast display via I2C or SPI.",
    category: "display",
    categoryLabel: "Display",
    icon: "📺",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8d/SSD1306_OLED_module_with_0.96_inch_screen.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 129,
    project: "ECE Department Inventory",
    tech: ["SSD1306", "I2C / SPI", "Adafruit Library"],
    features: ["128x64 pixel resolution", "0.96 inch screen", "I2C & SPI interface", "Ultra-low power consumption", "No backlight needed"]
  },

  // ─── SENSORS ──────────────────────────────

  {
    id: 6,
    name: "Smoke Sensor (MQ Series)",
    description: "MQ-2/MQ-135 gas and smoke detection sensor. Detects LPG, smoke, alcohol, propane, hydrogen, methane. Analog and digital output.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "💨",
    image: "https://upload.wikimedia.org/wikipedia/commons/2/20/MQ-2_Smoke_Sensor.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 79,
    project: "ECE Department Inventory",
    tech: ["MQ-2 / MQ-135", "Analog + Digital Out", "5V Logic"],
    features: ["Detects smoke, LPG, methane", "Analog and digital output", "Adjustable sensitivity", "Fast response time", "Simple Arduino interface"]
  },
  {
    id: 7,
    name: "Soil Moisture Sensor",
    description: "Capacitive or resistive soil moisture sensor. Measures water content in soil for smart irrigation and agriculture projects.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "🌱",
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Soil_Moisture_Sensor_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 59,
    project: "ECE Department Inventory",
    tech: ["Resistive / Capacitive", "Analog Out", "Arduino Compatible"],
    features: ["Measures soil water content", "Analog voltage output", "LED power indicator", "Adjustable threshold", "Suitable for plant monitoring"]
  },
  {
    id: 8,
    name: "Fire Detection Sensor (Flame Sensor)",
    description: "Infrared flame sensor that detects fire and flame sources. Sensitive to wavelengths between 760nm and 1100nm. Ideal for fire alarm systems.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "🔥",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flame_Sensor_Module_Arduino.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 59,
    project: "ECE Department Inventory",
    tech: ["IR Phototransistor", "760–1100nm", "Digital + Analog Out"],
    features: ["Detects flame/fire source", "Digital and analog output", "Detection angle ~60°", "Adjustable sensitivity", "Response time < 0.5s"]
  },
  {
    id: 9,
    name: "IR Sensor (Infrared Obstacle Sensor)",
    description: "Infrared obstacle detection sensor for short-range object detection. Widely used in robotics, line followers, and proximity sensing.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "📡",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/IR_Sensor_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 49,
    project: "ECE Department Inventory",
    tech: ["IR Emitter + Receiver", "Digital Output", "5V Logic"],
    features: ["2–30cm detection range", "Digital output signal", "Adjustable range", "Wide operating voltage", "Used in line follower robots"]
  },
  {
    id: 10,
    name: "Ultrasonic Sensor (HC-SR04)",
    description: "HC-SR04 ultrasonic ranging module. Measures distance from 2cm to 400cm using sonar. Non-contact, high accuracy.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "🔊",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Ultrasonic_Sensor_HC-SR04.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 69,
    project: "ECE Department Inventory",
    tech: ["HC-SR04", "40kHz Ultrasonic", "5V Logic"],
    features: ["2cm–400cm range", "3mm accuracy", "Trigger + Echo pins", "Non-contact measurement", "Low power consumption"]
  },
  {
    id: 11,
    name: "LDR Sensor (Light Sensor)",
    description: "Light Dependent Resistor module for ambient light sensing. Resistance decreases as light intensity increases.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "☀️",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/bb/LDR_Light_Dependent_Resistor.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 39,
    project: "ECE Department Inventory",
    tech: ["LDR / Photoresistor", "Analog Out", "Comparator Module"],
    features: ["Detects light intensity", "Analog output", "Wide light range sensing", "Adjustable threshold", "Auto light control projects"]
  },
  {
    id: 12,
    name: "DHT11 / DHT22 Temperature & Humidity Sensor",
    description: "Digital temperature and humidity sensor. DHT11 for basic use, DHT22 for higher accuracy. Widely used in weather stations and HVAC projects.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "🌡️",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/ee/DHT11_Humidity_%26_Temperature_Sensor.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 79,
    project: "ECE Department Inventory",
    tech: ["DHT11 / DHT22", "Single Wire Protocol", "3.3–5V"],
    features: ["Temperature: 0–50°C (DHT11)", "Humidity: 20–90% RH", "Digital single-wire output", "Low power consumption", "Arduino library available"]
  },
  {
    id: 13,
    name: "Rain Sensor Module",
    description: "Detects rainfall using conductive pads. Outputs analog and digital signals based on rain intensity. Used in smart weather and irrigation systems.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "🌧️",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Rain_Sensor_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 59,
    project: "ECE Department Inventory",
    tech: ["Conductive Pad", "Analog + Digital Out", "LM393 Comparator"],
    features: ["Detects rainfall", "Analog and digital output", "Adjustable sensitivity", "5V power supply", "Weatherproof pad"]
  },
  {
    id: 14,
    name: "Vibration Sensor",
    description: "Piezoelectric vibration sensor module detects shocks, vibrations, and knocks. Used in tamper detection and vibration measurement.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "〰️",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Vibration_Sensor_Module_SW-420.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 49,
    project: "ECE Department Inventory",
    tech: ["SW-420 / Piezo", "Digital Out", "3.3–5V"],
    features: ["Detects vibration and shock", "Digital output", "Adjustable sensitivity", "Compact size", "Tamper alarm systems"]
  },
  {
    id: 15,
    name: "Tilt Sensor",
    description: "Ball-type tilt sensor that detects orientation change. Simple on/off switch mechanism triggered by tilt angle.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "↕️",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Tilt_Sensor_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 39,
    project: "ECE Department Inventory",
    tech: ["Ball Switch", "Digital Out", "5V Logic"],
    features: ["Detects tilt/orientation", "On/Off digital output", "No moving parts (mercury-free)", "Small & lightweight", "Suitable for robotics"]
  },
  {
    id: 16,
    name: "MPU6050 Accelerometer & Gyroscope",
    description: "6-axis IMU sensor combining 3-axis accelerometer and 3-axis gyroscope. Used in drones, robotics, and motion tracking via I2C.",
    category: "sensor",
    categoryLabel: "Sensor",
    icon: "🔄",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ae/MPU-6050_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 99,
    project: "ECE Department Inventory",
    tech: ["MPU6050", "I2C Interface", "3.3–5V"],
    features: ["3-axis accelerometer", "3-axis gyroscope", "I2C communication", "16-bit ADC resolution", "Used in drones & gesture control"]
  },

  // ─── RELAY MODULES ────────────────────────

  {
    id: 17,
    name: "Single Channel Relay Module",
    description: "1-channel 5V relay module for switching AC/DC loads. Controlled by microcontroller signal. Includes flyback diode for protection.",
    category: "relay",
    categoryLabel: "Relay & Switching",
    icon: "⚡",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/eb/1_Channel_Relay_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 59,
    project: "ECE Department Inventory",
    tech: ["5V Relay", "Optocoupler Isolated", "10A / 250VAC"],
    features: ["Controls AC/DC devices", "Optocoupler isolation", "LED status indicator", "NO/NC/COM terminals", "Arduino compatible"]
  },
  {
    id: 18,
    name: "Two Channel Relay Module",
    description: "2-channel relay module. Control two independent loads from a microcontroller. Ideal for home automation projects.",
    category: "relay",
    categoryLabel: "Relay & Switching",
    icon: "⚡⚡",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/31/2_Channel_Relay_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 89,
    project: "ECE Department Inventory",
    tech: ["5V Dual Relay", "Optocoupler Isolated", "10A / 250VAC"],
    features: ["2 independent channels", "Active-low trigger", "LED indicators per channel", "Screw terminal connectors", "Home automation use"]
  },
  {
    id: 19,
    name: "Four Channel Relay Module",
    description: "4-channel relay module for controlling 4 independent electrical loads. Perfect for smart home and industrial automation.",
    category: "relay",
    categoryLabel: "Relay & Switching",
    icon: "🔌",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5b/4_Channel_Relay_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 129,
    project: "ECE Department Inventory",
    tech: ["5V Quad Relay", "Optocoupler Isolated", "10A / 250VAC"],
    features: ["4 independent relay channels", "Active-low inputs", "LED status per relay", "Wide input voltage", "Industry standard terminals"]
  },

  // ─── MOTORS & DRIVERS ─────────────────────

  {
    id: 20,
    name: "DC Motor",
    description: "Standard brushed DC motor for general-purpose robotics and projects. Runs on 3–12V DC. Requires motor driver for microcontroller control.",
    category: "motor",
    categoryLabel: "Motors",
    icon: "⚙️",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/DC_Motor_Electric.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 79,
    project: "ECE Department Inventory",
    tech: ["Brushed DC", "3–12V", "Requires Driver IC"],
    features: ["3–12V operating range", "High torque variant available", "Compact size", "Simple two-wire control", "Used in robotics & fans"]
  },
  {
    id: 21,
    name: "Servo Motor",
    description: "SG90 / MG90S servo motor for precise angular position control. Controlled by PWM signal from microcontroller. 0–180° rotation.",
    category: "motor",
    categoryLabel: "Motors",
    icon: "🔩",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d6/TowerPro_MG90S_servo_motor.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 99,
    project: "ECE Department Inventory",
    tech: ["SG90 / MG90S", "PWM Control", "5V Logic"],
    features: ["0–180° rotation", "PWM signal control", "Position feedback", "Includes mounting horns", "Plastic or metal gear variants"]
  },
  {
    id: 22,
    name: "Motor Driver Module (L293D / L298N)",
    description: "Dual H-bridge motor driver IC for controlling DC and stepper motors. Supports two DC motors or one stepper. Enable/direction pins.",
    category: "motor",
    categoryLabel: "Motors",
    icon: "🎛️",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/4e/L298N_Motor_Driver_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 119,
    project: "ECE Department Inventory",
    tech: ["L293D / L298N", "Dual H-Bridge", "Up to 2A per channel"],
    features: ["Controls 2 DC or 1 stepper motor", "PWM speed control", "Direction control pins", "Built-in flyback diodes", "12V motor power input"]
  },

  // ─── COMMUNICATION MODULES ────────────────

  {
    id: 23,
    name: "Bluetooth Module (HC-05 / HC-06)",
    description: "HC-05/HC-06 Bluetooth serial module. Enables wireless serial communication between Arduino and phone/PC. Master-slave configurable.",
    category: "communication",
    categoryLabel: "Communication",
    icon: "📶",
    image: "https://upload.wikimedia.org/wikipedia/commons/e/e7/HC-05_Bluetooth_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 149,
    project: "ECE Department Inventory",
    tech: ["HC-05 / HC-06", "Bluetooth 2.0 Classic", "UART Serial"],
    features: ["Bluetooth 2.0 + EDR", "UART serial interface", "Pairable with Android/PC", "Master & Slave modes (HC-05)", "Range up to 10m"]
  },
  {
    id: 24,
    name: "RFID Module (RC522)",
    description: "MFRC522 RFID reader/writer module. Reads Mifare 13.56 MHz RFID cards and tags. Used in access control and attendance systems.",
    category: "communication",
    categoryLabel: "Communication",
    icon: "📟",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/RFID_Module_RC522.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 129,
    project: "ECE Department Inventory",
    tech: ["MFRC522", "13.56 MHz RFID", "SPI Interface"],
    features: ["13.56 MHz Mifare cards", "SPI communication", "Read & Write capability", "Includes RFID card + keychain", "Access control systems"]
  },
  {
    id: 25,
    name: "GSM Module (SIM800L / SIM900A)",
    description: "GSM/GPRS module for sending SMS, making calls, and internet via UART. SIM800L compact; SIM900A for dev boards.",
    category: "communication",
    categoryLabel: "Communication",
    icon: "📱",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3f/SIM800L_GSM_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 249,
    project: "ECE Department Inventory",
    tech: ["SIM800L / SIM900A", "GSM / GPRS", "AT Commands"],
    features: ["Send & receive SMS", "Make voice calls", "GPRS data connectivity", "AT command interface", "Works with standard SIM"]
  },
  {
    id: 26,
    name: "GPS Module (NEO-6M)",
    description: "u-blox NEO-6M GPS module with ceramic antenna. Provides location coordinates via UART. Used in vehicle tracking and navigation.",
    category: "communication",
    categoryLabel: "Communication",
    icon: "🗺️",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d4/NEO-6M_GPS_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 299,
    project: "ECE Department Inventory",
    tech: ["u-blox NEO-6M", "NMEA Protocol", "UART 9600 baud"],
    features: ["Latitude & longitude output", "Ceramic patch antenna", "UART serial output", "Cold start acquisition", "Vehicle & asset tracking"]
  },
  {
    id: 27,
    name: "ESP8266 Wi-Fi Module",
    description: "Standalone ESP8266 Wi-Fi module (ESP-01). Adds Wi-Fi connectivity to any microcontroller via AT commands over UART.",
    category: "communication",
    categoryLabel: "Communication",
    icon: "📡",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/84/ESP-01_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 99,
    project: "ECE Department Inventory",
    tech: ["ESP8266 ESP-01", "Wi-Fi 802.11 b/g/n", "AT Commands / UART"],
    features: ["Wi-Fi connectivity", "UART AT command control", "Client and AP mode", "Ultra-low power sleep", "IoT sensor gateway"]
  },

  // ─── POWER COMPONENTS ─────────────────────

  {
    id: 28,
    name: "Batteries",
    description: "Assorted rechargeable and non-rechargeable batteries. Includes 9V, AA, AAA, 18650 Li-ion, and LiPo packs for project power supply.",
    category: "power",
    categoryLabel: "Power",
    icon: "🔋",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Battery_AA_HR6.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 49,
    project: "ECE Department Inventory",
    tech: ["Li-ion / LiPo / Alkaline", "Various Voltages", "Rechargeable Options"],
    features: ["Multiple voltage options", "Li-ion 18650 available", "LiPo for compact builds", "9V snap connector", "Reusable for projects"]
  },
  {
    id: 29,
    name: "Solar Panels",
    description: "Small photovoltaic solar panels (3V–12V) for solar energy harvesting projects. Used in IoT sensor nodes and off-grid systems.",
    category: "power",
    categoryLabel: "Power",
    icon: "☀️",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Small_Solar_Panel_Module.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 149,
    project: "ECE Department Inventory",
    tech: ["Polycrystalline / Monocrystalline", "3V–12V Output", "Solar Charging"],
    features: ["3V to 12V variants", "Compact panel size", "Suitable for charging circuits", "High efficiency cells", "Outdoor energy harvest"]
  },
  {
    id: 30,
    name: "Power Adapters",
    description: "5V and 12V DC power adapters/SMPS for project power supply. Regulated output with barrel jack connector.",
    category: "power",
    categoryLabel: "Power",
    icon: "🔌",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Power_Adapter_5V_2A.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 79,
    project: "ECE Department Inventory",
    tech: ["SMPS Regulated", "5V / 12V DC", "Barrel Jack 5.5mm"],
    features: ["Regulated 5V or 12V output", "2A current capacity", "Short circuit protection", "Barrel jack output", "Desktop project power"]
  },

  // ─── AUDIO ────────────────────────────────

  {
    id: 31,
    name: "Buzzer",
    description: "Active and passive piezoelectric buzzers for sound alerts in Arduino projects. Active buzzer needs only DC; passive buzzer needs PWM for tones.",
    category: "audio",
    categoryLabel: "Audio",
    icon: "🔔",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/19/Buzzer_Active_Passive.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 29,
    project: "ECE Department Inventory",
    tech: ["Active / Passive Piezo", "3–5V", "PWM Tone Generation"],
    features: ["Active: DC powered beep", "Passive: melody via PWM", "Loud 85dB output", "Low power consumption", "Alarm & notification use"]
  },

  // ─── PROTOTYPING ──────────────────────────

  {
    id: 32,
    name: "Breadboard",
    description: "Solderless prototyping breadboard. 830 tie-point full-size or 400 tie-point half-size. Connect components without soldering.",
    category: "prototyping",
    categoryLabel: "Prototyping",
    icon: "🧩",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/73/400_points_breadboard.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 59,
    project: "ECE Department Inventory",
    tech: ["Solderless", "830 / 400 Tie-Points", "Universal"],
    features: ["No soldering needed", "830 or 400 tie-points", "Power rail strips", "Jumper wire compatible", "Reusable"]
  },
  {
    id: 33,
    name: "Jumper Wires",
    description: "Male-to-male, male-to-female, and female-to-female jumper wire kits for prototyping. 10cm–30cm lengths.",
    category: "prototyping",
    categoryLabel: "Prototyping",
    icon: "〰️",
    image: "https://upload.wikimedia.org/wikipedia/commons/5/5d/Jumper_wires.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 39,
    project: "ECE Department Inventory",
    tech: ["M-M / M-F / F-F", "22 AWG", "10–30cm"],
    features: ["M-M, M-F, F-F variants", "40-piece kit", "10cm to 30cm lengths", "Color coded", "Breadboard & sensor compatible"]
  },
  {
    id: 34,
    name: "LEDs (Various Colors)",
    description: "Assorted 5mm and 3mm through-hole LEDs in red, green, blue, yellow, white. Standard indicator and display use.",
    category: "prototyping",
    categoryLabel: "Prototyping",
    icon: "💡",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/cb/RBG_LED.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 19,
    project: "ECE Department Inventory",
    tech: ["5mm / 3mm LED", "2.0–3.3V Forward", "20mA Max"],
    features: ["5 colors included", "5mm and 3mm variants", "2.0–3.3V forward voltage", "20mA operating current", "Status indicator use"]
  },
  {
    id: 35,
    name: "Push Buttons",
    description: "Tactile push button switches (6x6mm and 12x12mm). Momentary contact, SPST type. Used for user input in all Arduino/MCU projects.",
    category: "prototyping",
    categoryLabel: "Prototyping",
    icon: "🔘",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Tactile_Push_Buttons.jpg",
    type: ["temporary", "permanent"],
    tempPrice: 20,
    permPrice: 9,
    project: "ECE Department Inventory",
    tech: ["SPST Tactile", "6x6mm / 12x12mm", "Active Low / High"],
    features: ["Momentary contact", "6x6 and 12x12mm sizes", "4-pin DIP package", "Low actuation force", "Breadboard compatible"]
  }

];
